### ISSUE TITLE
undefined url in referrer ofscrape.js

### ISSUE THREAD

**Issue by UnknownSilence** [Kaelinator/skyward-rest#13]
C:\Users\Trent Hardy\Desktop\skywardtest\node_modules\skyward-rest\lib\scrape.js:53
    const referer = url.split('/')
                        ^

TypeError: Cannot read property 'split' of undefined
    at Scraper (C:\Users\Trent Hardy\Desktop\skywardtest\node_modules\skyward-rest\lib\scrape.js:53:25)
    at Object.<anonymous> (C:\Users\Trent Hardy\Desktop\skywardtest\node_modules\skyward-rest\index.js:14:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Trent Hardy\Desktop\skywardtest\main.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

```javascript
const skyward = require('skyward-rest')

const url = "https://skyward.kleinisd.net/scripts/wsisa.dll/WService=wsEAplus/seplog01.w"
const userId = '*********'
const password = '**********'

skyward(url)(userId, password)
    .then(student => {
        student.scrape('S1')
            .then(console.log) // => [Object Array]
            .then(() => student.close())
    })
```
User and password are correct, but censored for obvious reasons.

it appears to me that the scrape.js file of your module isn't taking in the url parameter from the main.js file that is calling the node module.
```javascript
const Scraper = (url) =>
  (sId, pass) => {

    let loginInfo, secretCode, gradebook, browser, args

    const referer = url.split('/')
      .slice(0, -1)
      .concat('httploader.p?file=sfgradebook001.w')
      .join('/')
```

There also appears to be an unused import of Promise from bluebird in your index.js here:

```javascript
const Promise = require('bluebird')
```

**Comment by Kaelinator** [comment]
Hmm. I wouldn't spend too much time on the master branch at the moment. Most of the development is going on in impl-faas. Once that's merged, all this code will be obsolete.
